name: CI/CD - Build and Deploy to ECS

on:
  push:
    branches: [test] # Or your deployment branch

env:
  AWS_REGION: ${{ secrets.AWS_REGION }}
  ECR_REPO: ${{ secrets.ECR_REPO }}

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

        # Set up Docker Buildx
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Download .env from S3
        run: aws s3 cp ${{ secrets.S3_ENV_PATH }} .env

      - name: Log in to Amazon ECR
        id: login-ecr
        uses: aws-actions/amazon-ecr-login@v2

      - name: Build and Push Docker image
        run: |
          IMAGE_TAG=latest
          ECR_URI=${{ steps.login-ecr.outputs.registry }}/${{ secrets.ECR_REPO }}

          docker buildx build \
          --platform linux/arm64 \
          -t $ECR_URI:$IMAGE_TAG \
          --push .
